# Introduction to NumPy

# 1. Importing and Creating Arrays

*   Import the numpy library as np.






In [ ]:
import numpy as np

*   Create a one-dimesional and two-dimensional array using np.array().


In [ ]:
# Create a 1D array

arr_1d = np.array([1,2,3,4,5])

# Create a 2D array

arr_2d = np.array([[1,2,3],[4,5,6]])

print("1D Array: ",arr_1d)

print("2D Array:\n",arr_2d)

1D Array:  [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


# 2. Basic Array Operations

*   Perform element-wise addition, subtraction, multiplication, and division on the arrays.



In [ ]:
  # Addition

  arr_sum = arr_1d + 5

  print("Element-wise addtion: ",arr_sum,"\n")

  # Subtraction

  arr_difference = arr_sum - 2

  print("Element-wise subtraction: ",arr_difference,"\n")

  # Multiplication

  arr_product = arr_difference * 3

  print("Element-wise multiplication: ",arr_product,"\n")

  # Division

  arr_division = arr_product / 3

  print("Element-wise division: ",arr_division,"\n")

Element-wise addtion:  [ 6  7  8  9 10] 

Element-wise subtraction:  [4 5 6 7 8] 

Element-wise multiplication:  [12 15 18 21 24] 

Element-wise division:  [4. 5. 6. 7. 8.] 



*   Using array indexing and slicing to extract specific elements or sub-arrays.



In [ ]:
  # Extract and Slice of Addition

  arr_subsum= arr_1d[1] + arr_1d[4]

  print("Sum of second and last element: ",arr_subsum,"\n")

  # Extract and Slice of Subtraction

  arr_subdiff = arr_1d[2] - arr_1d[4]

  print("Difference of third and last element: ",arr_subdiff,"\n")

  # Extract and Slice of Multiplication

  arr_subproduct = arr_1d[3] * arr_1d[4]

  print("Product of fourth and last element: ",arr_subproduct,"\n")

  # Extract and Slice of Division

  arr_subdivision = arr_1d[4] / arr_1d[1]

  print("Division of first and last element: ",arr_subdivision,"\n")

Sum of second and last element:  7 

Difference of third and last element:  -2 

Product of fourth and last element:  20 

Division of first and last element:  2.5 



# 3. Reshaping and Transposing Arrays

*   Use reshape() to change the shape of an array

In [ ]:
# Reshape 1D array to a 2D array

arr_3 = np.array([1,2,3,4,5,6,7,8,9,10])
reshaped_arr = arr_3.reshape(5,2)

print("Original 1D array: ",arr_3)
print("Reshaped 1D array to 2D array:\n",reshaped_arr)

Original 1D array:  [ 1  2  3  4  5  6  7  8  9 10]
Reshaped 1D array to 2D array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


*   Use transpose() to switch rows and columns of a 2D array.

In [ ]:
  # Transpose the 2D array

  transposed_arr = arr_2d.transpose()

  print("Transpossed 2D array:\n",transposed_arr)

Transpossed 2D array:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
  # Array Indexing and slicing

  print("Third element of 1D Array: ",arr_1d[2])
  print("Second row of 2D arrary: ", arr_2d[1,:])

Third element of 1D Array:  3
Second row of 2D arrary:  [4 5 6]


# 4. Activity:

*   Create a 3x3 array with values ranging from 1 to 9.

In [ ]:
  # NumPy library was already declared in the upper part of the notebook.

  act_array3x3 = np.arange(1, 10).reshape(3, 3)

  print(act_array3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


*   Find the sum, mean, and standard deviation of the array.

In [ ]:
  # Sum of the array
  sum_array3x3 = np.sum(act_array3x3)

  # Mean of the array
  mean_array3x3 = np.mean(act_array3x3)

  # Standard Deviation of the array
  std_array3x3 = np.std(act_array3x3)

  print("Sum of the array: ", sum_array3x3)
  print("Mean of the array: ",mean_array3x3)
  print("Standard deviation of the array: ",std_array3x3)

Sum of the array:  45
Mean of the array:  5.0
Standard deviation of the array:  2.581988897471611


*   Extract the subarray that consists of the first two rows and first two columns.

In [ ]:
  extracted_subarray3x3 = act_array3x3[:2, :2]

  print(extracted_subarray3x3)

[[1 2]
 [4 5]]
